/* Generated on 21/09/2026 20:50:06
   GENERATED FILE: do not edit. Edit build/uninstall-macros.template.js (or the MACROS
   table in build/build.py), then run: python build/build.py

   Macro: cleans up everything install-macros.js installs.
   - Removes hotbar slots 1-8 from EVERY user in the world (whether currently
     connected or not), without touching the rest of their personal hotbar; the slots
     that only the Game Masters get (9) are only removed from the GMs
   - Deletes the 10 macros installed by install-macros.js: the 5 trait-roll-*
     macros, custom-roll, private-message, and start-session (start-session has
     no hotbar slot to remove — only its Macro document gets deleted)
   - Also does a final one-time cleanup of the old simple-roll-* macros
     (slots 11-15), which were replaced by the custom-roll palette and are no
     longer reinstalled by install-macros.js at all (see LEGACY_* below)
   Asks for confirmation first, since this is destructive and irreversible.

   Macros are looked up by their technical identifier (flags.world.macroKey),
   never by their display name (freely renameable, so not a reliable lookup
   key) — see install-macros.js for the full rationale behind this split.

   NOTE: the icon SVG files generated under worlds/<world>/macro-icons/ are NOT
   deleted: Foundry v13 exposes no public file-deletion method (verified via
   Object.getOwnPropertyNames(FilePicker): browse/configurePath/createDirectory/
   upload all exist, but no delete). They are harmless leftovers and can be
   removed by hand from Foundry's file manager if desired. install-macros.js
   now reuses an existing file instead of recreating one on every reinstall, so
   they no longer accumulate over time. */

// ---- Translations: generated by build/build.py from lang/*.json, do not edit ----
const I18N_TEXTS = {
  "en": {"uninstall.done": "Cleanup finished for {users} user(s): {macros} macro(s) deleted.", "uninstall.gm_slots": "remove slot {range} from the hotbar of the Game Masters only;", "uninstall.intro": "This will, for ALL players in the world (connected or not):", "uninstall.irreversible": "This cannot be undone. Continue?", "uninstall.macros": "delete the macros installed by install-macros.js.", "uninstall.refresh": "Refresh the Foundry window (F5) for the removal of start-session to take effect.", "uninstall.slots": "remove slots {range} (and the old 11-15 if they are still around) from their hotbar (the rest of their hotbar is left alone);", "uninstall.title": "Cleanup"},
  "fr": {"uninstall.done": "Nettoyage terminé pour {users} utilisateur(s) : {macros} macro(s) supprimée(s).", "uninstall.gm_slots": "retirer l'emplacement {range} de la barre des meneurs de jeu seulement ;", "uninstall.intro": "Cette action va, pour TOUS les joueurs du monde (connectés ou non) :", "uninstall.irreversible": "Cette action est irréversible. Continuer ?", "uninstall.macros": "supprimer les macros installées par install-macros.js.", "uninstall.refresh": "Rafraîchis la fenêtre de Foundry (F5) pour que la suppression de start-session prenne effet.", "uninstall.slots": "retirer les emplacements {range} (et les anciens 11-15 s'ils traînent encore) de leur barre de raccourcis (le reste de leur barre n'est pas touché) ;", "uninstall.title": "Nettoyage"}
};
const t = (key, vars = {}) => {
  const lang = String(game.i18n?.lang ?? "en");
  for (const code of [lang, lang.split("-")[0], "en"]) {
    const table = I18N_TEXTS[code];
    if (!table) continue;
    let text = table[key];
    if (text === undefined && vars.n !== undefined) {
      text = table[`${key}.${new Intl.PluralRules(code).select(vars.n)}`] ?? table[`${key}.other`];
    }
    if (text !== undefined) return text.replace(/\{(\w+)\}/g, (match, name) => name in vars ? String(vars[name]) : match);
  }
  return key;
};
// ---- End of translations ----

// Technical identifiers of the macros currently installed by install-macros.js
// (generated from the MACROS table in build/build.py, same source as install-macros.js)
const INSTALLED_MACRO_KEYS = [
  "macro-1d4-joker", "macro-1d6-joker", "macro-1d8-joker", "macro-1d10-joker", "macro-1d12-joker",
  "custom-roll", "macro-spend-benny", "macro-private-message", "macro-give-bennies-to-players",
  "macro-session-start"
];

// Hotbar slots used by install-macros.js (generated, same source)
const INSTALLED_SLOTS = [1, 2, 3, 4, 5, 6, 7, 8];

// Hotbar slots that only the Game Masters get (install-macros.js gives them to the GMs only): they are
// cleared for the GMs only, so that what a player put in that slot is never touched.
const GM_ONLY_SLOTS = [9];

// Old simple-roll-* macros (replaced by the custom-roll palette): install-macros.js
// no longer installs these, but we clean them up here one last time if they're still around.
const LEGACY_MACRO_KEYS = ["macro-1d4", "macro-1d6", "macro-1d8", "macro-1d10", "macro-1d12"];
const LEGACY_SLOTS = [11, 12, 13, 14, 15];

(async () => {
  const confirmed = await foundry.applications.api.DialogV2.confirm({
    window: { title: t("uninstall.title") },
    content: `
      <p>${t("uninstall.intro")}</p>
      <ul>
        <li>${t("uninstall.slots", { range: "1-8" })}</li>
        <li>${t("uninstall.gm_slots", { range: "9" })}</li>
        <li>${t("uninstall.macros")}</li>
      </ul>
      <p>${t("uninstall.irreversible")}</p>
    `
  });
  if (!confirmed) return;

  // --- 1. Remove the installed slots from every user's hotbar ---
  // Rebuild each user's hotbar without the installed slots, then replace the whole field
  // ("recursive: false"): the "hotbar.-=N" deletion syntax is rejected by the hotbar field's
  // validator on this version of Foundry.
  for (const user of game.users) {
    const slotsToClear = [...INSTALLED_SLOTS, ...LEGACY_SLOTS, ...(user.isGM ? GM_ONLY_SLOTS : [])];
    const filteredHotbar = Object.fromEntries(
      Object.entries(user.hotbar).filter(([slot]) => !slotsToClear.includes(Number(slot)))
    );
    if (Object.keys(filteredHotbar).length !== Object.keys(user.hotbar).length) {
      await user.update({ hotbar: filteredHotbar }, { recursive: false });
    }
  }

  // --- 2. Delete the macros installed by install-macros.js (+ the old simple-roll-* ones) ---
  let deletedMacroCount = 0;
  for (const macroKey of [...INSTALLED_MACRO_KEYS, ...LEGACY_MACRO_KEYS]) {
    const macro = game.macros.find(m => m.getFlag("world", "macroKey") === macroKey);
    if (!macro) continue;
    await macro.delete();
    deletedMacroCount++;
  }

  ui.hotbar.render(true);
  ui.notifications.info(t("uninstall.done", { users: game.users.size, macros: deletedMacroCount }));
  // start-session registers its hooks only once per session (game._whisperReplyHooked):
  // deleting the macro here does not remove hooks already active in the current session.
  ui.notifications.warn(t("uninstall.refresh"));
})();
